### PR TITLE
Barebones implementation of comfyui

### PR DESCRIPTION
**Pull request by fylrid2**
image

This PR adds the possibility of generating images using Comfyui as an API instead of A1111. When clicking on the "SD webui" button up to the left there will be two buttons to chose your API mode. Choosing either one will hide irrelevant elements and show the relevant ones. This implementation should have zero impact on A1111 generation or any other features. In this menu the user should also choose what workflow they wanna use, I have added a sample workflow to the repo that has all placeholders in place. Available placeholders at the moment are the following:
- "%prompt%"
- "%negative_prompt%"
- "%cfg%"
- "%steps%"
- "%sampler%"
- "%scheduler%"
- "%model%"
- "%seed%"
- "%vae%"
- "%width%"
- "%height%"

However at this stage a lot of features are missing and there are definietly some improvements that could be made.

### Current missing features compared A1111

- Image to Image
- Hires 
I think thats all?

### Clear improvements that could be made moving forward

- As there are no api call for fetching models this has to be done instead by fetching the users model folder, currently though we are just using text inputs instead of dropdowns as the fetching hasn't been implemented, this is quite the annoying user experience.
- Improve the progress tracking allowing users to be able to see exactly how far into generation they are currently.
- Improving the styling and UX, like moving the upload workflow button somewhere more intuitive.
- Detecting wheter a placeholder is placed for a specific field and if it isn't, disable editing those t2i settings for better clarity.
- and of course as typing this I forgot the other stuff ...

I left some "TODO" comments in the code aswell that could be looked at.

### Chat GPT Translation

このPRは、A1111の代わりにComfyuiをAPIとして使用して画像を生成する機能を追加します。左上の「SD webui」ボタンをクリックすると、APIモードを選択するための2つのボタンが表示されます。どちらかを選択すると、関連のない要素が非表示になり、関連する要素が表示されます。この実装は、A1111の生成や他の機能に全く影響を与えないはずです。このメニューでは、ユーザーが使用するワークフローを選択する必要もあり、リポジトリにすべてのプレースホルダーが配置されたサンプルワークフローを追加しました。現在利用可能なプレースホルダーは以下の通りです：

- "%prompt%"
- "%negative_prompt%"
- "%cfg%"
- "%steps%"
- "%sampler%"
- "%scheduler%"
- "%model%"
- "%seed%"
- "%vae%"
- "%width%"
- "%height%"
しかし、現段階では多くの機能が欠けており、改良の余地があることは確かです。

### A1111と比較して現在欠けている機能
- 画像から画像へ
- 高解像度
- これで全部だと思います。
### 今後改善できる明確な点
- モデルを取得するためのAPI呼び出しがないため、ユーザーのモデルフォルダーを取得する必要がありますが、現在はドロップダウンの代わりにテキスト入力を使用しています。これが実装されていないため、ユーザー体験がかなり煩わしいものとなっています。
- 進行状況の追跡を改善し、現在どの程度生成が進んでいるかを正確に確認できるようにする。
- スタイリングとUXの改善。例えば、ワークフローアップロードボタンをもっと直感的な場所に移動するなど。
- 特定のフィールドにプレースホルダーが配置されているかどうかを検出し、配置されていない場合はそれらのt2i設定の編集を無効にして明確さを向上させる。
- そしてもちろん、この文章を書いている間に他の改善点を忘れてしまいました...

コードには「TODO」コメントもいくつか残してあるので、そちらも確認してください。

### CODE REVIEW

**Comment by FPZKryddan** [comment]
Forgot to mention in the post but there is no support for loras currently as comfyui doesn't allow loras in text, this should be high priority to fix I think. Shouldn't be too dificult is just mostly the logistics and the UX of it that can be an issue.

**Comment by fylrid2** [comment]
Forgot to mention in the post but there is no support for loras currently as comfyui doesn't allow loras in text, this should be high priority to fix I think. Shouldn't be too dificult is just mostly the logistics and the UX of it that can be an issue.

**Comment by new-sankaku** [comment]
Thank you! ComfyUI is indeed quite challenging... I'll take a look at everything and aim to merge it. I think I can manage to do it by this weekend.

I plan to make a few minor changes:

I believe the model list can be implemented with the following:
Model: http://127.0.0.1:8188/object_info/CheckpointLoaderSimple
Sampling Method: http://127.0.0.1:8188/object_info/KSampler
There are other things that could be fetched, but I will leave them for now:

Lora: http://127.0.0.1:8188/object_info/LoraLoader

UpscaleModel: http://127.0.0.1:8188/object_info/UpscaleModelLoader

VAELoader: http://127.0.0.1:8188/object_info/VAELoader

Embeddings: http://127.0.0.1:8188/embeddings

I will try to make the toggle button for switching SD WebUI mode more intuitive.

Instead of hiding the API host and port when switching UIs, I will display them with clear labels to avoid confusion.

For the online/offline status in Information Control, since ComfyUI does not have a ping feature, I will send a request to Settings (http://127.0.0.1:8188/settings) to pseudo-check the online status.

Thank you very much for your cooperation!

**Comment by new-sankaku** [comment]
I'm still working on the ComfyUI features, but I'll accept the PR and hide the features for now. I've made it possible to load models, but I failed to generate images, so I'll try to make it a bit more user-friendly.

Thanks for the pull request!

**Pull request merged**
